package com.cloudinary.transformation

sealed class FormatType(private val value: String) {
    class auto : FormatType("auto")
    class ai : FormatType("ai")
    class gif : FormatType("gif")
    class bmp : FormatType("bmp")
    class webp : FormatType("webp")
    class djvu : FormatType("djvu")
    class ps : FormatType("ps")
    class ept : FormatType("ept")
    class eps : FormatType("eps")
    class eps3 : FormatType("eps3")
    class fxb : FormatType("fbx")
    class flif : FormatType("flif")
    class gltf : FormatType("gltf")
    class heif : FormatType("heif")
    class heic : FormatType("heic")
    class ico : FormatType("ico")
    class indd : FormatType("indd")
    class jpg : FormatType("jpg")
    class jpe : FormatType("jpe")
    class jpeg : FormatType("jpeg")
    class jp2 : FormatType("jp2")
    class wdp : FormatType("wdp")
    class jxr : FormatType("jxr")
    class hdp : FormatType("hdp")
    class pdf : FormatType("pdf")
    class png : FormatType("png")
    class spd : FormatType("psd")
    class arw : FormatType("arw")
    class cr2 : FormatType("cr2")
    class svg : FormatType("svg")
    class tga : FormatType("tga")
    class tif : FormatType("tif")
    class tiff : FormatType("tiff")
    class avif : FormatType("avif")
    class video3g2 : FormatType("3g2")
    class video3gp : FormatType("3gp")
    class videoAvi : FormatType("avi")
    class videoFlv : FormatType("flv")
    class videoM3u8 : FormatType("m3u8")
    class videoTs : FormatType("ts")
    class videoMov : FormatType("mov")
    class videoMkv : FormatType("mkv")
    class videoMp4 : FormatType("mp4")
    class videoMpeg : FormatType("mpeg")
    class videoMpd : FormatType("mpd")
    class videoMxf : FormatType("mxf")
    class videoOgv : FormatType("ogv")
    class videoWebm : FormatType("webm")
    class videoWmv : FormatType("wmv")
    class videoM2ts : FormatType("m2ts")
    class videoMts : FormatType("mts")
    class audioAac : FormatType("aac")
    class audioAiff : FormatType("aiff")
    class audioAmr : FormatType("amr")
    class audioFlac : FormatType("flac")
    class audioM4a : FormatType("m4a")
    class audioMp3 : FormatType("mp3")
    class audioOgg : FormatType("ogg")
    class audioOpus : FormatType("opus")
    class audioWav : FormatType("wav")
    class custom(customFormat: String) : FormatType(customFormat)

    override fun toString(): String {
        return value
    }
}